# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Workflow for building JCONF website and deploying a Jekyll site to Vercel
name: Deploy JCONF website to Vercel

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  
  # Runs on pull requests for preview deployments
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-artifact@v4
        with:
          name: jconfwebsite
          path: _site

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: jconfwebsite
          path: _site
      - name: Debug _site directory
        if: github.event_name == 'pull_request'
        run: |
          echo "Contents of _site directory:"
          ls -la _site/
          echo "Checking for index.html:"
          ls -la _site/index.html || echo "index.html not found"
          echo "Checking for other files:"
          find _site -name "*.html" | head -5
          echo "Checking _site directory size:"
          du -sh _site/
          echo "First few lines of index.html:"
          head -10 _site/index.html || echo "Cannot read index.html"
      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'
      - name: Deploy to Vercel (Preview)
        if: github.event_name == 'pull_request'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod=false'
      - name: Comment PR with Preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && comment.body.includes('🚀 Preview deployment')
            );
            
            // Get the preview URL from Vercel action
            const previewUrl = process.env.VERCEL_URL || `https://jconfperu-pr-${context.issue.number}-dario-lunas-projects.vercel.app`;
            
            const body = `🚀 **Preview deployment ready!**
            
            **Unique Preview URL:** ${previewUrl}
            
            This is a unique preview deployment for PR #${context.issue.number}.
            The preview will be automatically updated when you push new commits to this PR.
            
            **Features:**
            - ✅ Unique URL for this PR
            - ✅ Automatic updates on new commits
            - ✅ Safe testing environment
            - ✅ Automatic cleanup when PR is closed
            
            ---
            *This is an automated preview deployment for testing purposes.*`;
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }